//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteResumes
    {
        public int UserId { get; set; }
        public int ResumeId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Resumes Resumes { get; set; }
        public virtual Users Users { get; set; }
    }
}
