//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vacancyEntities : DbContext
    {
        public vacancyEntities()
            : base("name=vacancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Educations> Educations { get; set; }
        public virtual DbSet<EmploymentTypes> EmploymentTypes { get; set; }
        public virtual DbSet<FavoriteResumes> FavoriteResumes { get; set; }
        public virtual DbSet<FavoriteVacancies> FavoriteVacancies { get; set; }
        public virtual DbSet<Interviews> Interviews { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<ResponseStatuses> ResponseStatuses { get; set; }
        public virtual DbSet<ResumeEducations> ResumeEducations { get; set; }
        public virtual DbSet<Resumes> Resumes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
        public virtual DbSet<VacancyResponses> VacancyResponses { get; set; }
        public virtual DbSet<VacancySkills> VacancySkills { get; set; }
        public virtual DbSet<WorkExperiences> WorkExperiences { get; set; }
    }
}
