//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsRead { get; set; }
        public string NotificationType { get; set; }
        public Nullable<int> RelatedEntityId { get; set; }
        public string RelatedEntityType { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
