//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeEducations
    {
        public int Id { get; set; }
        public int ResumeId { get; set; }
        public string Institution { get; set; }
        public string Specialization { get; set; }
        public int EducationLevelId { get; set; }
        public Nullable<int> YearCompleted { get; set; }
    
        public virtual Educations Educations { get; set; }
        public virtual Resumes Resumes { get; set; }
    }
}
